version: '3'

services:
  simple-google-drive-postgres:
    extends:
      file: /test/docker/docker-compose.yml
      service: simple-google-drive-postgres

  simple-google-drive:
    image: node:20
    restart: unless-stopped
    working_dir: /app
    tty: true
    command: bash -c "npm i && npm start"
    network_mode: 'host'
    volumes:
      - ../src:/app/src
      - ../.env:/app/.env
      - ../package.json:/app/package.json
      - ../node_modules:/app/node_modules
      - ../nest-cli.json:/app/nest-cli.json
      - ../tsconfig.build.json:/app/tsconfig.build.json
      - ../tsconfig.json:/app/tsconfig.json
    depends_on:
      - simple-google-drive-postgres
